default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      workspace: "../../Project.xcworkspace",
      scheme: "FoodShare",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
  
  desc "Build for release"
  lane :release do
    build_app(
      workspace: "../../Project.xcworkspace",
      scheme: "FoodShare",
      export_method: "app-store"
    )
    upload_to_app_store
  end
end
